export const QUERY_MODEL_PROJECTION_CONSUMER_OPTIONS_TOKEN = "QUERY_MODEL_PROJECTION_CONSUMER_OPTIONS_TOKEN" as const;
export const QUERY_MODEL_PROJECTION_CONSUMER = "QUERY_MODEL_PROJECTION_CONSUMER" as const;
