export const KAFKAJS_CONSUMER_CONFIG_TOKEN = "KAFKAJS_CONSUMER_CONFIG_TOKEN" as const;
export const KAFKAJS_CONSUMER_SUBSCRIBE_TOPICS_TOKEN = "KAFKAJS_CONSUMER_SUBSCRIBE_TOPICS_TOKEN" as const;
export const KAFKAJS_CONSUMER_RUN_CONFIG_TOKEN = "KAFKAJS_CONSUMER_RUN_CONFIG_TOKEN" as const;
