export const GET_AGGREGATE_TYPES_TOKEN = "GET_AGGREGATE_TYPES_TOKEN" as const;
export const GET_AGGREGATE_IDS_TOKEN = "GET_AGGREGATE_IDS_TOKEN" as const;
export const GET_AGGREGATE_TOKEN = "GET_AGGREGATE_TOKEN" as const;
export const GET_DOMAIN_EVENTS_FOR_AGGREGATE_TOKEN = "GET_DOMAIN_EVENTS_FOR_AGGREGATE_TOKEN" as const;
