import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
const sidebars: SidebarsConfig = {
    sidebar: [
        {
            type: "category",
            label: "Getting started",
            items: [
                {
                    type: "autogenerated",
                    dirName: "getting-started"
                }
            ]
        },
        {
            type: "category",
            label: "Core concepts",
            items: [
                {
                    type: "autogenerated",
                    dirName: "core-concepts"
                }
            ]
        },
        {
            type: "category",
            label: "Advanced concepts",
            items: [
                {
                    type: "autogenerated",
                    dirName: "advanced-concepts"
                }
            ]
        },
        {
            type: "category",
            label: "Ports",
            items: [
                {
                    type: "autogenerated",
                    dirName: "ports"
                }
            ]
        },
        {
            type: "category",
            label: "Adapters",
            items: [
                {
                    type: "autogenerated",
                    dirName: "adapters"
                }
            ]
        },
        {
            type: "category",
            label: "Tutorial: NestJS",
            items: [
                {
                    type: "autogenerated",
                    dirName: "tutorial-nestjs"
                }
            ]
        }
    ]
};

export default sidebars;
